spring:
  application:
    name: devtrust

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: devtrust-correlation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.vsk.devtrust.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://localhost:5432/devtrust
    username: devtrust
    password: devtrust123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: devtrust

devtrust:

  ai:
    api-key: ${GROQ_API_KEY:test-api-key}
    api-url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.3-70b-versatile

  prometheus:
    url: http://localhost:9090
    service-name: devtrust-test-repo  # must match your GitHub repo name for correlation to work

  github:
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:test-webhook-secret}
  kafka:
    topics:
      deployments: devtrust.deployments
      anomalies: devtrust.anomalies
      incidents: devtrust.incidents
  correlation:
    window-seconds: 300   # correlate anomalies within 5 minutes of a deployment